services:
  - type: web
    name: golovolomka-bot
    env: node
    plan: free
    buildCommand: npm install && cd miniapp-3d && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        sync: false
